### PR TITLE
fix: update URL to new username

### LINKED ISSUE #232: Version Warn bug
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Have you ran the program with debug logging?

- [ ] I used `--log-level=debug` when running the program

### What went wrong?

Upon opening, it triggers the version warning despite being latest version, tried a redownload from the repo but still accours the same warning despite being on the latest version.

### Terminal output

2026-01-18 18:56:56 INFO  [jellyfin_rpc] Initializing Jellyfin-RPC
2026-01-18 18:56:57 WARN  [jellyfin_rpc::updates] You are not running the latest version of Jellyfin-RPC (Current: v1.3.4, Latest: vhttps://github.com/JustRadical/jellyfin-rpc/releases/tag/1.3.4)
2026-01-18 18:56:57 WARN  [jellyfin_rpc::updates] A newer version can be found at
2026-01-18 18:56:57 WARN  [jellyfin_rpc::updates] https://github.com/Radiicall/jellyfin-rpc/releases/latest
2026-01-18 18:56:57 WARN  [jellyfin_rpc::updates] This can be safely ignored if you are running a prerelease version
2026-01-18 18:56:57 INFO  [jellyfin_rpc] Connecting to Discord
2026-01-18 18:56:57 INFO  [jellyfin_rpc] Attempt 1: Trying to connect
2026-01-18 18:56:57 INFO  [jellyfin_rpc] Connected!

### Jellyfin-RPC version

 Windows Executable 1.3.4

### What OS are you using?

Windows 11 25H2

### What version is the Jellyfin server on?

10.11.5

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by van-sprundel**
Fixes #232

### CODE REVIEW

File: jellyfin-rpc-cli/src/updates.rs [hunk 1]
```diff
@@ -32,7 +32,7 @@ fn get_latest_github() -> Result<String, reqwest::Error> {
     let url = reqwest::blocking::get("https://github.com/Radiicall/jellyfin-rpc/releases/latest")?
         .url()
         .as_str()
-        .trim_start_matches("https://github.com/Radiicall/jellyfin-rpc/releases/tag/")
+        .trim_start_matches("https://github.com/Radiicall/jellyfin-rpc/releases/tag/v")
```
Comment (justradical) [inline jellyfin-rpc-cli/src/updates.rs]: Hey this does not in-fact fix that issue, the problem is i changed my username from Radiicall to JustRadical, you just have to modify the url to be `https://github.com/JustRadical/jellyfin-rpc/releases/tag/` in the code and with that you should probably also update any mention in those files of `https://github.com/Radiicall` to `https://github.com/JustRadical/`

**Review by JustRadical — CHANGES_REQUESTED** [review]

File: jellyfin-rpc-cli/src/updates.rs (hunk 1 above)
Comment (van-sprundel) [reply jellyfin-rpc-cli/src/updates.rs]: Whoops, you're right. Will make that change, thanks for the quick response.

It might also be cool to take a look at a self-updating snippet. I haven't done it in rust yet, but it seems these are fairly popular

- https://docs.rs/self-replace/latest/self_replace/
- https://crates.io/crates/self_update

Comment (justradical) [reply jellyfin-rpc-cli/src/updates.rs]: self updating is cool until your program gets managed by a 3rd party package manager (dnf, pacman, chocolatey, brew, etc) and accidentally fucks up everything, i think its fine to just display a warning

**Review by JustRadical — APPROVED** [review]
